package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/prime-radiant-inc/clipfan/internal/releaseflags"
)

const generatedHeader = "// Code generated by scripts/generate-ssh-release-gates.sh; DO NOT EDIT.\n"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	root, err := findRepoRoot()
	if err != nil {
		return err
	}

	transport, runtime, err := load(root)
	if err != nil {
		return err
	}
	if err := releaseflags.ValidateGateBundle(transport, runtime); err != nil {
		return err
	}

	transportGo, err := renderGoTransportGates(transport)
	if err != nil {
		return err
	}
	runtimeGo, err := renderGoRuntimeGates(runtime)
	if err != nil {
		return err
	}

	outputs := []struct {
		path    string
		content []byte
	}{
		{
			path:    "internal/releaseflags/ssh_transport_gates.go",
			content: transportGo,
		},
		{
			path:    "internal/releaseflags/ssh_runtime_gates.go",
			content: runtimeGo,
		},
		{
			path:    "apps/mac/Clipfan/Sources/Clipfan/GeneratedSSHTransportGates.swift",
			content: renderSwiftTransportGates(transport),
		},
		{
			path:    "apps/mac/Clipfan/Sources/Clipfan/GeneratedSSHRuntimeGates.swift",
			content: renderSwiftRuntimeGates(runtime),
		},
	}

	for _, output := range outputs {
		if err := writeFile(filepath.Join(root, output.path), output.content); err != nil {
			return err
		}
	}
	return nil
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		} else if !os.IsNotExist(err) {
			return "", err
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

func load(root string) (releaseflags.TransportGates, releaseflags.RuntimeGates, error) {
	transportFile, err := os.Open(filepath.Join(root, "release/ssh-transport-gates.json"))
	if err != nil {
		return releaseflags.TransportGates{}, releaseflags.RuntimeGates{}, err
	}
	defer transportFile.Close()

	transport, err := releaseflags.ReadTransportGates(transportFile)
	if err != nil {
		return releaseflags.TransportGates{}, releaseflags.RuntimeGates{}, err
	}

	runtimeFile, err := os.Open(filepath.Join(root, "release/ssh-runtime-gates.json"))
	if err != nil {
		return releaseflags.TransportGates{}, releaseflags.RuntimeGates{}, err
	}
	defer runtimeFile.Close()

	runtime, err := releaseflags.ReadRuntimeGates(runtimeFile)
	if err != nil {
		return releaseflags.TransportGates{}, releaseflags.RuntimeGates{}, err
	}

	return transport, runtime, nil
}

func renderGoTransportGates(gates releaseflags.TransportGates) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	b.WriteString("\n")
	b.WriteString("package releaseflags\n\n")
	b.WriteString("const (\n")
	fmt.Fprintf(&b, "\tPeerHTTPRuntimeDisabled = %t\n", gates.PeerHTTPRuntimeDisabled)
	fmt.Fprintf(&b, "\tConfigV2WriteEnabled = %t\n", gates.ConfigV2WriteEnabled)
	fmt.Fprintf(&b, "\tRemoteSecretWriteReleaseEnabled = %t\n", gates.RemoteSecretWriteReleaseEnabled)
	fmt.Fprintf(&b, "\tSSHPublicAddPeerSuccessEnabled = %t\n", gates.SSHPublicAddPeerSuccessEnabled)
	b.WriteString(")\n")
	return formatGoOutput("transport gates", b.Bytes())
}

func renderGoRuntimeGates(gates releaseflags.RuntimeGates) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	b.WriteString("\n")
	b.WriteString("package releaseflags\n\n")
	b.WriteString("const (\n")
	fmt.Fprintf(&b, "\tSSHReceivePrimitiveEnabled = %t\n", gates.SSHReceivePrimitiveEnabled)
	fmt.Fprintf(&b, "\tSSHSyncStreamEnabled = %t\n", gates.SSHSyncStreamEnabled)
	fmt.Fprintf(&b, "\tSSHPersistentCurrentEnabled = %t\n", gates.SSHPersistentCurrentEnabled)
	fmt.Fprintf(&b, "\tSSHSyncKeyRotationEnabled = %t\n", gates.SSHSyncKeyRotationEnabled)
	b.WriteString(")\n")
	return formatGoOutput("runtime gates", b.Bytes())
}

func renderSwiftTransportGates(gates releaseflags.TransportGates) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	b.WriteString("\n")
	b.WriteString("enum GeneratedSSHTransportGates {\n")
	fmt.Fprintf(&b, "    static let peerHTTPRuntimeDisabled = %t\n", gates.PeerHTTPRuntimeDisabled)
	fmt.Fprintf(&b, "    static let configV2WriteEnabled = %t\n", gates.ConfigV2WriteEnabled)
	fmt.Fprintf(&b, "    static let remoteSecretWriteReleaseEnabled = %t\n", gates.RemoteSecretWriteReleaseEnabled)
	fmt.Fprintf(&b, "    static let publicAddPeerSuccessEnabled = %t\n", gates.SSHPublicAddPeerSuccessEnabled)
	b.WriteString("}\n")
	return b.Bytes()
}

func renderSwiftRuntimeGates(gates releaseflags.RuntimeGates) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	b.WriteString("\n")
	b.WriteString("enum GeneratedSSHRuntimeGates {\n")
	fmt.Fprintf(&b, "    static let receivePrimitiveEnabled = %t\n", gates.SSHReceivePrimitiveEnabled)
	fmt.Fprintf(&b, "    static let syncStreamEnabled = %t\n", gates.SSHSyncStreamEnabled)
	fmt.Fprintf(&b, "    static let persistentCurrentEnabled = %t\n", gates.SSHPersistentCurrentEnabled)
	fmt.Fprintf(&b, "    static let syncKeyRotationEnabled = %t\n", gates.SSHSyncKeyRotationEnabled)
	b.WriteString("}\n")
	return b.Bytes()
}

func writeFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0644)
}

func formatGoOutput(name string, content []byte) ([]byte, error) {
	formatted, err := format.Source(content)
	if err != nil {
		return nil, fmt.Errorf("format generated Go output for %s: %w", name, err)
	}
	return formatted, nil
}
