// Code generated by scripts/generate-ssh-release-gates.sh; DO NOT EDIT.

package releaseflags

const (
	PeerHTTPRuntimeDisabled = false
	ConfigV2WriteEnabled = false
	RemoteSecretWriteReleaseEnabled = false
	SSHPublicAddPeerSuccessEnabled = false
)
