// Code generated by scripts/generate-ssh-release-gates.sh; DO NOT EDIT.

package releaseflags

const (
	PeerHTTPRuntimeDisabled         = true
	ConfigV2WriteEnabled            = true
	RemoteSecretWriteReleaseEnabled = false
	SSHPublicAddPeerSuccessEnabled  = false
)
