// Code generated by scripts/generate-ssh-release-gates.sh; DO NOT EDIT.

package releaseflags

const (
	SSHReceivePrimitiveEnabled  = false
	SSHSyncStreamEnabled        = false
	SSHPersistentCurrentEnabled = false
	SSHSyncKeyRotationEnabled   = false
)
