// Code generated by scripts/generate-ssh-release-gates.sh; DO NOT EDIT.

package releaseflags

const (
	SSHReceivePrimitiveEnabled  = true
	SSHSyncStreamEnabled        = true
	SSHPersistentCurrentEnabled = true
	SSHSyncKeyRotationEnabled   = false
)
