// Code generated by scripts/generate-ssh-release-gates.sh; DO NOT EDIT.

enum GeneratedSSHRuntimeGates {
    static let receivePrimitiveEnabled = true
    static let syncStreamEnabled = true
    static let persistentCurrentEnabled = true
    static let syncKeyRotationEnabled = false
}
