// Code generated by scripts/generate-ssh-release-gates.sh; DO NOT EDIT.

enum GeneratedSSHRuntimeGates {
    static let receivePrimitiveEnabled = false
    static let syncStreamEnabled = false
    static let persistentCurrentEnabled = false
    static let syncKeyRotationEnabled = false
}
