// Code generated by scripts/generate-ssh-release-gates.sh; DO NOT EDIT.

enum GeneratedSSHTransportGates {
    static let remoteSecretWriteReleaseEnabled = false
    static let publicAddPeerSuccessEnabled = false
}
